# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/pubsub.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/pubsub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/pubsub.proto\x12\x06pubsub\"5\n\x0ePublishRequest\x12\x12\n\ntopic_name\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"!\n\x0fPublishResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"=\n\x10SubscribeRequest\x12\x12\n\ntopic_name\x18\x01 \x01(\t\x12\x15\n\rreplay_preset\x18\x02 \x01(\t\"?\n\x05\x45vent\x12\x11\n\treplay_id\x18\x01 \x01(\t\x12\x12\n\ntopic_name\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t2|\n\x06PubSub\x12:\n\x07Publish\x12\x16.pubsub.PublishRequest\x1a\x17.pubsub.PublishResponse\x12\x36\n\tSubscribe\x12\x18.pubsub.SubscribeRequest\x1a\r.pubsub.Event0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.pubsub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUBLISHREQUEST']._serialized_start=30
  _globals['_PUBLISHREQUEST']._serialized_end=83
  _globals['_PUBLISHRESPONSE']._serialized_start=85
  _globals['_PUBLISHRESPONSE']._serialized_end=118
  _globals['_SUBSCRIBEREQUEST']._serialized_start=120
  _globals['_SUBSCRIBEREQUEST']._serialized_end=181
  _globals['_EVENT']._serialized_start=183
  _globals['_EVENT']._serialized_end=246
  _globals['_PUBSUB']._serialized_start=248
  _globals['_PUBSUB']._serialized_end=372
# @@protoc_insertion_point(module_scope)
