# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import pubsub_pb2 as proto_dot_pubsub__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'grpc package is {GRPC_VERSION}; generated code targets grpcio>={GRPC_GENERATED_VERSION}. '
        'Consider upgrading grpcio or regenerating with grpcio-tools to match.',
        RuntimeWarning,
        stacklevel=2,
    )


class PubSubStub(object):
    """Mock Salesforce-style Pub/Sub for CDC events
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/pubsub.PubSub/Publish',
                request_serializer=proto_dot_pubsub__pb2.PublishRequest.SerializeToString,
                response_deserializer=proto_dot_pubsub__pb2.PublishResponse.FromString)
        self.Subscribe = channel.unary_stream(
                '/pubsub.PubSub/Subscribe',
                request_serializer=proto_dot_pubsub__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=proto_dot_pubsub__pb2.Event.FromString)


class PubSubServicer(object):
    """Mock Salesforce-style Pub/Sub for CDC events
    """

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PubSubServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=proto_dot_pubsub__pb2.PublishRequest.FromString,
                    response_serializer=proto_dot_pubsub__pb2.PublishResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=proto_dot_pubsub__pb2.SubscribeRequest.FromString,
                    response_serializer=proto_dot_pubsub__pb2.Event.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pubsub.PubSub', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    if hasattr(server, 'add_registered_method_handlers'):
        server.add_registered_method_handlers('pubsub.PubSub', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PubSub(object):
    """Mock Salesforce-style Pub/Sub for CDC events
    """

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pubsub.PubSub/Publish',
            proto_dot_pubsub__pb2.PublishRequest.SerializeToString,
            proto_dot_pubsub__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pubsub.PubSub/Subscribe',
            proto_dot_pubsub__pb2.SubscribeRequest.SerializeToString,
            proto_dot_pubsub__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)
