# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: account_sync.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'account_sync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61\x63\x63ount_sync.proto\x12\x0b\x61\x63\x63ountsync\"\x80\x01\n\x0e\x41\x63\x63ountRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\r\n\x05phone\x18\x05 \x01(\t\x12\x15\n\rsource_system\x18\x06 \x01(\t\"\x1e\n\x0cSyncResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2[\n\x12\x41\x63\x63ountSyncService\x12\x45\n\x0bSyncAccount\x12\x1b.accountsync.AccountRequest\x1a\x19.accountsync.SyncResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_sync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNTREQUEST']._serialized_start=36
  _globals['_ACCOUNTREQUEST']._serialized_end=164
  _globals['_SYNCRESPONSE']._serialized_start=166
  _globals['_SYNCRESPONSE']._serialized_end=196
  _globals['_ACCOUNTSYNCSERVICE']._serialized_start=198
  _globals['_ACCOUNTSYNCSERVICE']._serialized_end=289
# @@protoc_insertion_point(module_scope)
